### ISSUE TITLE
Fine tune the default reporting policy

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_csp#13]
The existing default reporting policy seems to be too strict. What we need is for there to be a reasonably secure policy as the default, and for the help strings to give some good examples of what to use in different situations.

So I'd like to turn this on in a reasonably busy site and gather some stats on the issues. And then work through each issue and decide whether that class of issue should be fixed, or whether the policy should be relaxed as it is an acceptable use case. Then whatever policy we come up with should be the default.

**Comment by suankan** [comment]
Implemented by commit 4fec19299676f50a63201c07f3f6dc397bac311c
