### ISSUE TITLE
Supported Moodle plugin

### ISSUE THREAD

**Issue by mudrd8mz** [catalyst/moodle-local_csp#20]
The currently uploaded version into the Moodle plugins directory has Moodle 2.9 set as the only supported version. The plugin seems to work well in 3.2. As per the policy https://docs.moodle.org/dev/Plugin_contribution_checklist#Supported_Moodle_versions we can only approve plugins supporting more recent versions.

Please edit the version record https://moodle.org/plugins/pluginversion.php?id=13267&action=edit and set all supported versions explicitly (i.e. add 3.0, 3.1 and 3.2 too).

**Comment by brendanheywood** [comment]
thanks heaps @mudrd8mz I've fixed that now, and I'm cleaning up other minor ci issues too
