### ISSUE TITLE
Bg with long urls

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_csp#25]
[Tue Oct 01 10:09:12.441723 2019] [php7:notice] [pid 14030] [client 127.0.0.1:41510] Default exception handler: Error writing to database Debug: ERROR:  value too long for type character varying(256)
INSERT INTO mdl_local_csp (documenturi,blockeduri,violateddirective,timecreated,sha1hash,failcounter) VALUES($1,$2,$3,$4,$5,$6) RETURNING id
[array (
  'documenturi' => 'http://moodle.local/course/edit.php?id=2',
  'blockeduri' => 'http://moodle.local/theme/yui_combo.php?3_17_2%2Fdatatable-base%2Fassets%2Fskins%2Fsam%2Fdatatable-base_css&amp;3_17_2%2Fdatatable-message%2Fassets%2Fskins%2Fsam%2Fdatatable-message_css&amp;3_17_2%2Fdatatable-sort%2Fassets%2Fskins%2Fsam%2Fdatatable-sort_css&amp;3_17_2%2Fresize-base%2Fassets%2Fskins%2Fsam%2Fresize-base_css',
  'violateddirective' => 'style-src-elem',
  'timecreated' => 1569888552,
  'sha1hash' => '311fd4ed659252bb228544400725c504ac04e38b',
  'failcounter' => 1,
)]

**Comment by Peterburnett** [comment]
Fixed in PR #26
