### ISSUE TITLE
violateddirective DB field too short

### ISSUE THREAD

**Issue by JoelDSmith** [catalyst/moodle-local_csp#44]
I'm seeing a similar thing as #25, but now for the `violateddirective` field

With 9 URLs whitelisted for `script-src`, we've blown right past the `256` limit through to `315`. And there's a good chance it will be larger in future.

**Comment by brendanheywood** [comment]
Do you have a curl command or something which triggers this so we can easily reproduce? I suspect we'll need to swap the url to a text field, and then add a new field which is a hash of the url for the db index like we did with the crawler

**Comment by JoelDSmith** [comment]
Not seeing an issues with the URL fields - `violateddirective` is the problem.

`script-src about: data: blob: 'unsafe-inline' 'unsafe-eval' 'self' https://catalyst-analytics.net https://www.google-analytics.com https://cqu.logrocket.com https://www.wiris.net https://backpack.openbadges.org https://s.ytimg.com https://gdata.youtube.com https://www.youtube.com https://cdnjs.cloudflare.com`

This is the directive - it's simply too long to fit within `violateddirective`.

**Comment by brendanheywood** [comment]
Ah right, yeah

I'd also like to split it up into lots of fine grained admin settings so you can see what it going on without having to deal with a raw policy directly

https://github.com/catalyst/moodle-local_csp/issues/31

**Comment by JoelDSmith** [comment]
Interestingly, as part of replicating and fixing this, I found that different browsers send different things. Chrome seemed to trim the `violateddirective` to only include the `script-src-elem`; same with Firefox with `script-src` (looks like Firefox doesn't have CSP3 support). 

Edge (EdgeHTML) however sent the entire line with the whitelisted URLs included. If a record already existed in the database when Edge sent a report though, it didn't try to insert even though the `violateddirective` would've technically been different.

Either way, PR incoming.
