### ISSUE TITLE
totara test fail: install.xml is different to the generated version

### ISSUE THREAD

**Issue by kristian-94** [catalyst/moodle-local_csp#46]
We need to edit and save the install.xml file. 

> There was 1 failure:
> 
> 1) tool_xmldb_instal_xml_testcase::test_all_install_xml_files_formatted_correctly
> XMLDB file 'totara/local/csp/db/install.xml' is different to the generated version, please edit the file in XMLDB editor and save it.
> Failed asserting that false is true.
> 
> admin/tool/xmldb/tests/install_xml_test.php:52
> lib/phpunit/classes/base_testcase.php:600
> lib/phpunit/classes/advanced_testcase.php:68
> 
> To re-run:
>  vendor/bin/phpunit tool_xmldb_instal_xml_testcase admin/tool/xmldb/tests/install_xml_test.php

This is a similar problem to https://github.com/catalyst/moodle-tool_objectfs/issues/278

**Comment by danmarsden** [comment]
latest code fixes this.
