### ISSUE TITLE
Turn all the CSP policies into config settings

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-local_csp#5]
we want to be able to turn each setting on and off, and also turn them on for reporting first, and then alter for real. So each policy item should eb a drop down with 'None' 'Report', 'Fully on'

**Comment by brendanheywood** [comment]
Ok on reflection this will be much simpler and more flexible if we just have two text fields, 1 for the report policy we are testing, and 1 for the policy we are enforcing. If either is empty we don't send that particular header

**Comment by suankan** [comment]
This issue was addressed by developing inside of branch 'individual_config_settings' which was approved and merged into master.
