### ISSUE TITLE
Sorting by Top Violation Sources doesn't work 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-local_csp#50]
When trying to sort by Top Violation Sources I get  the following error

Debug info: ERROR: column "highestviolaters" does not exist
LINE 11: ORDER BY highestviolaters DESC, blockeduri D...
^
SELECT
id, blockeduri, violateddirective, failcounter, timecreated
FROM (SELECT MAX(id) AS id,
blockeduri,
violateddirective,
SUM(failcounter) AS failcounter,
MAX(timecreated) AS timecreated
FROM mdl_local_csp
GROUP BY blockeduri, violateddirective) AS A
WHERE 1 = 1
ORDER BY highestviolaters DESC, blockeduri DESC, failcounter DESC LIMIT 30
[array (
)]
Error code: dmlreadexception

Error
Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 305 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 916 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1648 of /lib/tablelib.php: call to pgsql_native_moodle_database->get_records_sql()
line 1669 of /lib/tablelib.php: call to table_sql->query_db()
line 145 of /local/csp/csp_report.php: call to table_sql->out()

**Comment by mdjnelson** [comment]
This also happens with the 'Actions' column which really shouldn't be sortable.

**Comment by brendanheywood** [comment]
I'll close this, the report has had a fair bit of work and these columns are not really designed to be sorted in this way so they are disabled now
