### ISSUE TITLE
Database performance issues

### ISSUE THREAD

**Issue by nkuehn** [catalyst/moodle-local_csp#59]
Hi, 
we've been observing growing database peformance issues and are unable to open the CSP report page.  The database is a fully managed Google Cloud SQL that ran happily until now.  The Cloud SQL "Query Insights" feature reports the following normalized query as the top hitter in terms of overall time spent:

```sql
SELECT
  *
FROM
  m_local_csp
WHERE
  documenturi = $1
  AND blockeduri = $2
  AND violateddirective = $3
```

Our configuration only had headers in the  `Content-Security-Policy-Report-Only` config until now. I'll move them into the `Content-Security-Policy` config now, leaving the report-only box blank - It's not clear from the UI text or README whether that will stop the reporting. 

I have truncated the `m_local_csp` table now, that made it possible again to load the reports page. 

My nearest guess is that it is a bad idea to only run "report" level for a longer time because basically all traffic fills the statistics table?  

My impression is that this is more a documentation and UI copy problem at the root.  Protecting the reports table from getting crazy big would make sense nevertheless IMHO.

**Comment by brendanheywood** [comment]
This sounds more like some missing indexes. Shouldn't be too hard to add, pull requests welcome or if you can sponsor this that would be cool

The reporting and the enforcing should be completely independant

**Comment by nkuehn** [comment]
Thanks for the information! My "solution" for now was to adjust the actual content security policy so that not every page hit is a reporting-worth issue.  Rather a bugfix.   

I can't realistically contribute a PR due to complete lack of knowledge about moodle internals.  I'll think about wording for the README.

**Comment by brendanheywood** [comment]
It is worth stating that ideally you should have near zero reports. If you are consistently getting reports then you should either make a decision to add them to the policy, or you should fix the content. There is little point in collecting lots of reports for no reason, and the collector itself has a performance impact.

**Comment by nkuehn** [comment]
Exactly.  But seemingly  even a relatively experienced IT person (here=me) can run into such "most stupid possible user fault" situation when they are overrun with topics to keep an eye on :-)
