### ISSUE TITLE
Indicate status of this plugin

### ISSUE THREAD

**Issue by luisdev** [catalyst/moodle-local_csp#77]
https://moodle.org/plugins/local_csp/versions lists 2019100100 (2019100100) as the most recent version of this plugin, with support for up to Moodle v3.7.

The https://github.com/catalyst/moodle-local_csp/blob/master/README.md file only mentions "Moodle 3.3 to 3.7".

Is this plugin supported in Moodle 3.9 and up? If not and the plugin is "retired", please add a note to this effect somewhere, like the moodle.org plugin page or here on github.

**Comment by keevan** [comment]
Hi @luisdev, thanks for reporting this issue. 

This plugin, according to its version.php should have support up to Moodle 4.0, and so the readme and releases should be updated to reflect that.

Please feel free to submit a PR for the changes, but otherwise we will update this once we get the chance.

Cheers.

**Comment by luisdev** [comment]
Thanks. So has the plugin been tested in all the latest supported versions of Moodle? 
Can it be installed in 3.9 and 4.0?

**Comment by keevan** [comment]
The ci running on this repository tests all the way up to the Moodle master branch yes.

It should be okay to install in 39 and 40. That said, please feel free to create an issue if you encounter something unexpected. 🙂

**Comment by luisdev** [comment]
I have installed version 2022060300 on my Moodle 3.9.17+ (Build: 20221011) test server and it seems to be ok. I will post any issues that I find as I test.

**Comment by luisdev** [comment]
It seems like the version on https://moodle.org/plugins/local_csp/ is out of date. I used the version from github.com.
Please update https://moodle.org - or add a note that the plugin should be obtained from github.com, not moodle.org.

**Comment by danmarsden** [comment]
@luisdev all catalyst plugins will always have their latest versions in github, we use git to deploy plugins internally. We have been slowly rolling out an auto deploy to moodle.org plugins db to help, but it will always be the case that the latest code is in github. Thanks!
